// inline function
#include<iostream>

inline int product(int x, int y)
{
 return(x*y);
}
int main()
{
 int a,b;
 clrscr();
 cout<<"\nEnter two numbers : ";
 cin>>a>>b;
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 cout<<"\nThe product of a and b is "<<product(a,b);
 return 0;
}